# Read the docs here: https://pre-commit.com and http://jorisroovers.github.io/gitlint/
# Install hooks to your clone:
#   $ pre-commit install --install-hooks
# and
#   $ pre-commit install --install-hooks -t commit-msg

default_stages: [commit]
# TODO Add excludes to the list below.
# Typically C++/Python projects need `build/` directory
#exclude: 'build/'
fail_fast: false

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
        args: ['--unsafe']
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        name: Commit message check
        language: python
        entry: gitlint --msg-filename
        stages: [commit-msg]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
